### ISSUE TITLE
Migrations are dissonant

### ISSUE THREAD

**Issue by szynszyliszys** [arkency/devsnap#12]
Migration 'ChangeColumnName' is trying to change column "login" that doesn't exist.

**Comment by andrzejkrzywda** [comment]
@siaw23 is this something you can help with?

**Comment by siaw23-retired** [comment]
yes, i'll fix it when i get home. @andrzejkrzywda

**Comment by siaw23-retired** [comment]
fixed in ac89c5c

**Comment by mpraglowski** [comment]
Fixed in Put users in descending chronological order #9
